export {default as Topbar} from './global/Topbar';
export {default as Sidebar} from './global/Sidebar';
export {default as Dashboard} from './dashboard/dashboard';
export {default as Team} from './team/team';
export {default as Invoices} from './invoices/invoices';
export {default as Contacts} from './contacts/contacts';
export {default as Bar} from './bar/bar';
export {default as Form} from './form/form';
// export {default as Line} from './line/line';
export {default as Pie} from './pie/pie';
export {default as FAQ} from './faq/faq';
// export {default as Geography} from './geography/geography';
export {default as Calendar} from './calendar/calendar';
